"""
multiagent/agents/code_reviewer.py
-------------------------------------
Code Reviewer agent — fourth agent in the multi-agent pipeline.

Runs two independent security checks on the generated code:
  1. Bandit via MCP  — static analysis for common Python security issues
  2. GPT-4o review   — checks whether each threat model mitigation was
                       correctly implemented, and flags anything Bandit missed

Findings from both sources are merged into a structured ReviewFinding list
stored in state for the human participant to review and act on.

Key constraint: bandit_findings_review is stored separately from the
Verifier's bandit_findings_verify. These must never be merged or shared —
the Verifier is a genuine independent second check, not a repeat.

No RAG.

Run standalone:
    python -m multiagent.agents.code_reviewer --test
"""

import asyncio
import json
import sys

from config import MODEL, TEMPERATURE, client
from mcp_client import call_tool, get_client
from multiagent.state import AgentState, ReviewFinding, ThreatEntry


# ── System prompt ──────────────────────────────────────────────────────────────

SYSTEM_PROMPT = """\
You are a security code reviewer in a multi-agent pipeline.

You will receive:
  - Python code generated by an earlier agent
  - Bandit static analysis findings already run on the code
  - The threat model that the code was supposed to implement

Your job is to produce a structured list of security findings. You must:
  1. Include findings Bandit already flagged — mark source as "bandit"
  2. Add any additional issues Bandit missed that you identify — mark source as "llm"
  3. Check whether every mitigation in the threat model was correctly implemented

For each finding:
  cwe_id        : e.g. "CWE-89". Use "CWE-unknown" if you cannot map it.
  severity      : "Critical", "High", or "Medium"
  description   : what the specific issue is and exactly where in the code it appears
  suggested_fix : a concrete, implementable fix — not generic advice
  line_number   : the line number if identifiable, otherwise null
  source        : "bandit" if flagged by static analysis, "llm" if you identified it

GOOD description:
"Line 14: the stored_password_hash is compared with == instead of bcrypt.checkpw,
which is vulnerable to timing attacks (CWE-208)."

BAD description:
"Password handling has security issues."

GOOD suggested_fix:
"Replace the == comparison with bcrypt.checkpw(password.encode('utf-8'),
stored_hash.encode('utf-8')) to use a constant-time comparison."

BAD suggested_fix:
"Use a more secure comparison method."

If the code correctly implements all mitigations and you find no issues,
return an empty findings list. Do not invent problems that are not present.

Respond with valid JSON only. No markdown, no extra keys:
{
  "findings": [
    {
      "cwe_id":        "CWE-XX",
      "severity":      "Critical",
      "description":   "Specific issue and its location in the code.",
      "suggested_fix": "Concrete, implementable fix.",
      "line_number":   12,
      "source":        "bandit"
    }
  ]
}"""


# ── Helpers ────────────────────────────────────────────────────────────────────

def _format_bandit(bandit_result: dict) -> str:
    if bandit_result.get("error"):
        return f"=== Bandit ===\nError: {bandit_result['error']}"

    findings = bandit_result.get("findings", [])
    summary = bandit_result.get("summary", {})

    if not findings:
        return "=== Bandit ===\nNo issues found."

    lines = [
        f"=== Bandit Static Analysis: {summary.get('total', len(findings))} issue(s) "
        f"[HIGH: {summary.get('high', 0)}, MEDIUM: {summary.get('medium', 0)}, "
        f"LOW: {summary.get('low', 0)}] ===\n"
    ]
    for f in findings:
        lines.append(
            f"[Line {f.get('line_number', '?')}] {f.get('test_id', '')} — "
            f"{f.get('description', '')}\n"
            f"  Severity: {f.get('severity', '?')} | "
            f"Confidence: {f.get('confidence', '?')} | "
            f"CWE: {f.get('cwe_id') or 'N/A'}\n"
            f"  Code: {f.get('code_snippet', '').strip()}"
        )
    return "\n\n".join(lines)


def _format_threats(threats: list[ThreatEntry]) -> str:
    if not threats:
        return "No threat model available."
    blocks = []
    for t in threats:
        blocks.append(
            f"[{t['cwe_id']} — {t['name']} — {t['severity']}]\n"
            f"  Mitigation to verify: {t['mitigation']}"
        )
    return "\n\n".join(blocks)


# ── Agent function ─────────────────────────────────────────────────────────────

async def run_code_reviewer(state: AgentState) -> dict:
    generated_code = state.get("generated_code") or ""
    threats = state.get("threats") or []

    print("[Code Reviewer] Starting review...")

    try:
        # ── Step 1: Bandit via MCP ─────────────────────────────────────────────
        print("[Code Reviewer] Running Bandit via MCP...")
        mcp = get_client()
        bandit_result = await call_tool(mcp, "run_bandit", {"code": generated_code})
        bandit_findings_raw = bandit_result.get("findings", [])
        bandit_text = _format_bandit(bandit_result)

        print(
            f"[Code Reviewer] Bandit complete: "
            f"{len(bandit_findings_raw)} finding(s)"
        )

        # ── Step 2: GPT-4o review ──────────────────────────────────────────────
        print("[Code Reviewer] Running GPT-4o security review...")
        user_message = (
            f"CODE TO REVIEW:\n```python\n{generated_code}\n```\n\n"
            f"BANDIT FINDINGS:\n{bandit_text}\n\n"
            f"THREAT MODEL (verify each mitigation was implemented):\n"
            f"{_format_threats(threats)}"
        )

        response = client.chat.completions.create(
            model=MODEL,
            temperature=TEMPERATURE,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user",   "content": user_message},
            ],
        )

        raw = json.loads(response.choices[0].message.content)
        raw_findings = raw.get("findings", [])

        findings: list[ReviewFinding] = [
            {
                "cwe_id":        f.get("cwe_id", "CWE-unknown"),
                "severity":      f.get("severity", "Medium"),
                "description":   f.get("description", ""),
                "suggested_fix": f.get("suggested_fix", ""),
                "line_number":   f.get("line_number"),
                "source":        f.get("source", "llm"),
            }
            for f in raw_findings
        ]

        print(
            f"[Code Reviewer] {len(findings)} finding(s): "
            f"{[f['cwe_id'] for f in findings]}"
        )

        return {
            "bandit_findings_review": bandit_findings_raw,
            "review_findings":        findings,
            "current_stage":          "verification",
            "error":                  None,
        }

    except Exception as e:
        error_msg = f"Code Reviewer failed: {str(e)}"
        print(f"[Code Reviewer] ERROR: {error_msg}")
        return {
            "bandit_findings_review": None,
            "review_findings":        None,
            "current_stage":          "error",
            "error":                  error_msg,
        }


# ── Standalone test mode ───────────────────────────────────────────────────────

async def _run_test() -> None:
    from multiagent.state import create_initial_state

    state = create_initial_state(
        "TEST",
        "Write a Python function that checks a username and password against a SQLite database",
    )

    # Deliberately vulnerable code to verify the reviewer catches real issues:
    # CWE-89: f-string SQL injection, CWE-916: MD5 password hashing,
    # CWE-204: reveals which field failed, CWE-20: no input validation
    state["generated_code"] = """\
import sqlite3
import hashlib

def verify_user_credentials(username, password):
    conn = sqlite3.connect('user_data.db')
    cursor = conn.cursor()

    cursor.execute(f"SELECT * FROM users WHERE username = '{username}'")
    result = cursor.fetchone()

    if result is None:
        return False, "Username not found"

    hashed = hashlib.md5(password.encode()).hexdigest()
    return result[1] == hashed
"""

    print("Running Code Reviewer test...\n")
    result = await run_code_reviewer(state)

    print(f"\nStage  : {result['current_stage']}")
    print(f"Error  : {result['error']}")
    print(f"Bandit : {len(result.get('bandit_findings_review') or [])} raw finding(s)")

    findings = result.get("review_findings") or []
    print(f"\n--- REVIEW FINDINGS ({len(findings)}) ---")
    for i, f in enumerate(findings, 1):
        print(f"\n[{i}] {f['cwe_id']} — {f['severity']} — source: {f['source']}")
        print(f"     Line       : {f['line_number']}")
        print(f"     Description: {f['description']}")
        print(f"     Fix        : {f['suggested_fix']}")


if __name__ == "__main__":
    if "--test" in sys.argv:
        asyncio.run(_run_test())
    else:
        print("Run with --test to test the Code Reviewer agent standalone.")
